#!/usr/bin/env bash
# displays hour 0-12 and minute 1-59
HOUR=0
while [ $HOUR -lt 13 ]
do
	echo "Hour: $HOUR"
	MINUTE=1
	while [ $MINUTE -lt 60 ]
	do
		echo $MINUTE
		(( MINUTE+=1 ))
	done
	(( HOUR+=1 ))
done
