#!/usr/bin/env bash
# This script display info about a file
FILE=school
if [ -f "$FILE" ]; then
	echo "school file exists"
	if [ -s "$FILE" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	echo "school is a regular file"
elif [ -d "$FILE" ]; then
	echo "school file exists"
	echo "school file is not empty" 
else
	echo "school file does not exist"
fi
